"""
This type stub file was generated by pyright.
"""

from ._ta_lib import __TA_FUNCTION_NAMES__

_func_obj_mapping = ...
def Function(function_name, *args, **kwargs):
  ...

__all__ = ["Function", "_get_defaults_and_docs"] + __TA_FUNCTION_NAMES__
