"""
This type stub file was generated by pyright.
"""

def test_streaming(): # -> None:
  ...

def test_streaming_pandas(): # -> None:
  ...

def test_CDL3BLACKCROWS(): # -> None:
  ...

def test_CDL3BLACKCROWS_pandas(): # -> None:
  ...

def test_MAXINDEX(): # -> None:
  ...

